### PR TITLE
(SERVER-1406) medium catalog

### PR DESCRIPTION
**Pull request by cprice404**
This commit adds a new role called `by_size::medium`.  The catalog generated by this role contains many more `package`, `user`, and other resources in an effort to get us up to something a bit more real-world.  The contents of the catalog were loosely based on a real catalog that Jeremy compiled from ops, so the various counts of different resource types are in the general ballpark of the ones that we saw in that catalog.  For more details see the Jira ticket.

### CODE REVIEW

**Comment by camlow325** [comment]
I set this up on a CentOS 7 vmpooler vm with puppetserver 2.4.0 and puppet-agent 1.5.3.  The agent run appeared to run fine for the most part.  I browed to the installed tomcat server to see that it was functional.  I did see one error in the agent output:

```
Notice: /Stage[main]/Profile::Sysop::Packages::Python_virtualenv/Package[python-virtualenv]/ensure: created
Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install python-pip' returned 1: Error: Nothing to do
Error: /Stage[main]/Profile::Sysop::Packages::Python_pip/Package[python-pip]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install python-pip' returned 1: Error: Nothing to do
```

This seemed to be benign though in that the agent run continued on successfully.  A second agent run was successful as well.

**Comment by cprice404** [comment]
Hmmm.  Probably an ordering issue between epel and pip.  I'll maybe try to repro and fix but that doesn't sound like a blocker necessarily.

**Comment by cprice404** [comment]
testing this additional commit that adds an epel dependency to a few packages that I think may need it.

**Comment by cprice404** [comment]
Squashed in that commit and rebased onto latest master.  Adding epel dependency to pip and jq fixed those first-run errors for me.

**Comment by camlow325** [comment]
:shipit:

**Pull request merged**
